config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts
    
  resources :comments 

  root 'posts#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    user ||= User.new

    if !user.new_record?
        can :manage, :all
    else
        can :view, Post
    end
    
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :post
  
end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :comments
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments

  def full_name
    "#{first_name} #{last_name}".lstrip
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  respond_to :js 

  def edit
    @comment = Comment.find(params[:id])
    authorize! :edit, @comment
    respond_with @comment
  end

  def create
    authorize! :create, Comment
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    respond_with @comment
  end

  def update
    @comment = Comment.find(params[:id])
    authorize! :edit, @comment 
    @comment.update_attributes(comment_params)
    respond_with @comment 
  end

  def destroy
    @comment = Comment.find(params[:id])
    authorize! :destroy, @comment
    @comment.destroy
    respond_with @comment 
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :post_id, :body)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  respond_to :html

  def index
    authorize! :view, Post
    @posts = Post.includes(:user, comments: :user).order(created_at: :desc).page(params[:page])
    respond_with @posts
  end

  def show
    authorize! :view, Post 
    @post = Post.find(params[:id])
    respond_with @post 
  end
  
  def new
    authorize! :create, Post
    @post = Post.new
    respond_with @post
  end

  def edit
    @post = Post.find(params[:id])
    authorize! :edit, @post
    respond_with @post 
  end

  def create
    authorize! :create, Post
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to posts_path(page: params[:page])
    else
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])
    authorize! :edit, @post 
    if @post.update_attributes(post_params)
      redirect_to posts_path(page: params[:page])
    else
      render :edit 
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize! :destroy, @post
    @post.destroy
    redirect_to posts_path(page: params[:page])
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/create.js.erb

$("#comments-container").html(
   "<%= raw escape_javascript( render('posts/comments', post: @comment.post ) ) %>"
);

$('#comment_body').val('');
$('#add-comment-container').collapse('hide');

app/views/comments/destroy.js.erb
$("#comments-container").html(
   "<%= raw escape_javascript( render('posts/comments', post: @comment.post ) ) %>"
);

$('#comment_body').val('');
$('#comment_body').data("wysihtml5").editor.clear();
$('#add-comment-container').collapse('hide');

app/views/comments/edit.js.erb
$("#comment-container-<%= @comment.id %>").html(
   "<%= raw escape_javascript( render('posts/edit_comment', comment: @comment, post: @comment.post ) ) %>"
);

$('#add-comment-container').collapse('show');

app/views/comments/update.js.erb
$("#comment-container-<%= @comment.id %>").html(
   "<%= raw escape_javascript( render('posts/comment', comment: @comment ) ) %>"
);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Brivity Messaging</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name='description' content='Description'>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= yield :style %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class='container-fluid'>
      <%= render partial: "shared/navigation" %>

      <%= yield %>

    </div>

    <%= yield :script %>

  </body>
</html>

app/views/posts/_comment.html.erb
<div class='col-sm-12'>
  <span><%= comment.user.full_name %> - <%= comment.created_at.to_s(:humanized_ago) %></span>
  
  <div class='pull-right'>
    <% if user_signed_in? %>
      <% if can?(:edit, comment) %>
        <%= link_to 'Edit', edit_comment_path(comment), remote: true %>
        <%= link_to 'Delete', comment_path(comment), method: :delete, remote: true, data: {confirm: 'Are you sure you want to delete this comment?'} %>
      <% end %>
    <% end %>
  </div>

</div>

<div class='col-sm-12'>

  <div class='col-sm-11'>
    <span><%= comment.body %></span>
  </div>
  
</div>

app/views/posts/_comments.html.erb
<% post.comments.includes(:user).order(:created_at).each do |comment| %>
  <div class='row' id="comment-container-<%= comment.id %>">
    <%= render 'posts/comment', comment: comment %>
  </div>
<% end %>

app/views/posts/_edit_comment.html.erb
<div class='well collapse' id='add-comment-container'>
  <%= form_for comment, remote: true, html: {class: 'form-horizontal'} do |f| %>
    <%= f.hidden_field :post_id %>

    <div class='form-group'>
      <%= f.text_area :body, class: 'form-control', style: 'height: 20em', placeholder: 'Comment' %>
    </div>

    <div class='form-group text-right'>
      <%= f.submit 'Submit', class: 'btn btn-primary btn-sm' %>
      <%= link_to 'Cancel', post_path(post), class: 'btn btn-default btn-sm', title: 'Cancel' %>
    </div>
  <% end %>
</div>

app/views/posts/_form.html.erb
<div class='row'>

  <div class="col-sm-offset-1 col-sm-10">
    
    <%= form_for @post, html: {id: 'form-post', class: 'form-horizontal', role: 'form'} do |f| %>

      <%= hidden_field_tag :page, params[:page] %>

      <%= render "shared/error_messages", target: @post %>

      <div class="form-group">
        <%= f.label :title, class: 'col-sm-1 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :title, class: 'form-control', required: true, placeholder: 'Title' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-12 col-lg-12">
          <%= f.text_area :body, class: 'form-control', rows: '20' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-12 text-center">
          <%= f.submit class: "btn btn-primary btn-sm" %>
          <%= link_to 'Back', posts_path, class: 'btn btn-default btn-sm' %>
        </div>
      </div>
      
    <% end %>

  </div>

</div>

app/views/posts/_post.html.erb
<div class='col-sm-12'>
  <h3><%= @post.title %></h3>
</div>
<div class='col-sm-12'>
  <div><%= post.user.full_name %> - <%= @post.created_at.to_s(:humanized_ago) %></div>
  

  <% if user_signed_in? %>
  
    <div class='pull-right'>
      
      <% if can?(:edit, @post) %>
        <%= link_to 'Edit', edit_post_path(@post), title: 'Edit this post.' %>
        <% if @post.comments.blank? %>
          <%= link_to 'Delete', post_path(@post), method: :delete, remote: true, data: {confirm: 'Are you sure you want to delete this Post?'} %>
        <% end %>
      <% end %>

    </div>

  <% end %>

</div>
<div class='col-sm-12'>
  <span><%= @post.body %></span>
</div>

app/views/posts/_posts_table.html.erb
<div class='row' >
  <div class='col-sm-12'>
    <div class='pull-right'><%= paginate posts %></div>
  </div>
</div>

<table class='table'>
  <thead>
    <tr>
      <th>Title</th>
      <th class='text-center'>Comments</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% if posts.present? %>
      <% posts.each do |post| %>
        <tr>
          <td>
            <div><%= link_to post.title, post_path(post), title: post.title %></div>
            <div><%= post.user.full_name %>, <%= post.created_at.to_s(:humanized_ago) %></div>
          </td>

          <td class='text-center'>
            <div><%= pluralize(post.comments.length, 'Comment') %></div>
          </td>
          
          <td class='nowrap'>
            <% if can?(:edit, post) %>
              <%= link_to 'Edit', edit_post_path(post, page: params[:page]), title: 'Edit Post' %>
            <% end %>
            <% if can?(:delete, post) %>
              <%= link_to 'Delete', post_path(post, page: params[:page]), data: {confirm: "Are you sure?"}, method: :delete, title: 'Delete Post' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr><td colspan='3'>No Posts Found</td></tr>
    <% end %>
  </tbody>
</table>

<div class='row'  style='font-weight: bold;'>
  <div class='col-sm-12'>
    <hr/>
    <div class='pull-right'><%= paginate posts %></div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'posts/form' %>

app/views/posts/index.html.erb
<div class='row'>

  <div class='col-sm-offset-1 col-sm-10'>
    <h4>Posts</h4>
    <% if can? :edit, Post %>
      <%= link_to "Add a New Post", new_post_path, role: "button", title: 'New Post' %>
    <% else %>
      <span>[You must be signed in to add a post]</span>
    <% end %>
  </div>

  <div class="col-sm-offset-1 col-sm-10">
    
    <div id='posts-table-container'>
      <%= render 'posts/posts_table', posts: @posts %>
    </div>

  </div>
</div>

app/views/posts/new.html.erb
<%= render 'posts/form' %>

app/views/posts/show.html.erb
<div class='row'>

  <div class="col-sm-offset-1 col-sm-10">

    <div class="col-sm-12">
      <div id='post-container'>
        <%= render 'posts/post', post: @post %>
      </div>
    </div>

    <div class='col-sm-12'>
      <h4 class='inline'>Comments</h4>
      
      <div id='comments-container'>
        <%= render 'posts/comments', post: @post %>
      </div>

      <% if can? :create, Comment %>
        <%= link_to 'Add a Comment', '#add-comment-container', role: "button", data: {toggle: "collapse"} %>

        <%= render 'posts/edit_comment', comment: Comment.new(post: @post), post: @post %>


      <% else %>
        <span>[You must be signed in to add a comment]</span>
      <% end %>

    </div>

  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>  
  <div id="errorExplanation">  
    <h4><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h4>  
    <ul>  
      <% target.errors.full_messages.each do |msg| %>  
        <li><%= msg %></li>  
      <% end %>  
    </ul>  
  </div>  
<% end %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-inverse" role="navigation">
   <div class="container-fluid">

      <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
            <span class="sr-only">Toggle Navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
         </button>
         <%= link_to 'Brivity Messaging', root_path, class: "navbar-brand" %>
      </div>

      <div class="collapse navbar-collapse" id="navbar-collapse">

         <ul class="nav navbar-nav navbar-right">

            <% if current_user.blank? %>
               <li>
                  <%= link_to 'Sign Up', new_user_registration_path %>
               </li>
               <li>
                  <%= link_to( 'Sign In', new_user_session_path ) %>
               </li>

            <% else %>
               <li>

                  <%= link_to( raw("#{current_user.email} <span class='caret'></span>"), '#', class: 'btn dropdown-toggle', data: {toggle: 'dropdown'}) %>

                  <ul id='dropdown-login' class='dropdown-menu'>
                     <li>
                        <%= link_to 'Profile', edit_user_registration_path %>
                     </li>
                     <li>
                        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
                     </li>
                  </ul>
               </li>

            <% end %>
         </ul>

      </div><!-- /.navbar-collapse -->

   </div>
</nav>